export const WEB3_LOADED = "WEB3_LOADED"
export const WALLET_ADDRESS_LOADED = "WALLET_ADDRESS_LOADED"
export const WALLET_BALANCE_LOADED = "WALLET_BALANCE_LOADED"

// NFT TYPES
export const NFT_CONTRACT_LOADED = "NFT_CONTRACT_LOADED"

//NFT MARKETPLACE TYPES
export const NFT_MARKETPLACE_CONTRACT_LOADED = "NFT_MARKETPLACE_CONTRACT_LOADED"
