export const WEB3_LOADED = "WEB3_LOADED"
export const WALLET_ADDRESS_LOADED = "WALLET_ADDRESS_LOADED"

// NFT TYPES
export const NFT_CONTRACT_LOADED = "NFT_CONTRACT_LOADED"
export const MINTED_NFT_LOADED = "MINTED_NFT_LOADED"
export const OWNED_NFT_LOADED = "OWNED_NFT_LOADED"
export const UNSOLD_NFT_LOADED = "UNSOLD_NFT_LOADED"
export const PURCHASED_SUCCESSFULLY = "PURCHASED_SUCCESSFULLY"
export const MINTED_SUCCESSFULLY = "MINTED_SUCCESSFULLY"

//NFT MARKETPLACE TYPES
export const NFT_MARKETPLACE_CONTRACT_LOADED = "NFT_MARKETPLACE_CONTRACT_LOADED"
